# Generated by Django 3.2.5 on 2021-09-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, help_text='null表示不是菜单,这个字段有值才表示二级菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_rbac.menu', verbose_name='所属菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='对于非菜单权限需要选择一个可以成为菜单的权限,用于做默认展开和选中的菜单', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='app_rbac.permission', verbose_name='关联某个权限'),
        ),
    ]
