# Generated by Django 3.2.5 on 2021-08-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rbac', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
