# Generated by Django 3.2.5 on 2021-08-31 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='地区')),
            ],
            options={
                'verbose_name': '地区',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='部门')),
            ],
            options={
                'verbose_name': '部门',
                'db_table': 'depart',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('name', models.CharField(max_length=64, verbose_name='真实姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('phone', models.CharField(max_length=32, verbose_name='电话')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.department', verbose_name='所属部门')),
                ('roles', models.ManyToManyField(blank=True, to='app_rbac.Role', verbose_name='所有角色')),
            ],
            options={
                'verbose_name': '员工',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1, verbose_name='期数')),
                ('price', models.IntegerField(default=1000000, verbose_name='项目款')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('memo', models.CharField(blank=True, max_length=256, null=True, verbose_name='项目说明')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.city', verbose_name='地区')),
                ('manger', models.ForeignKey(limit_choices_to={'depart__title': '管理层'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='crm.userinfo', verbose_name='项目经理')),
                ('principal', models.ManyToManyField(limit_choices_to={'depart__title': '管理层'}, related_name='principal', to='crm.UserInfo', verbose_name='负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '分公司',
                'db_table': 'company',
            },
        ),
    ]
