# Generated by Django 3.2.5 on 2021-09-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
