# Generated by Django 3.2.5 on 2021-08-30 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210829_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='manger',
            field=models.ForeignKey(limit_choices_to={'depart__title': '管理层'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='crm.userinfo', verbose_name='项目经理'),
        ),
        migrations.AlterField(
            model_name='company',
            name='principal',
            field=models.ForeignKey(limit_choices_to={'depart__title': '管理层'}, on_delete=django.db.models.deletion.CASCADE, related_name='principal', to='crm.userinfo', verbose_name='负责人'),
        ),
    ]
