# Generated by Django 3.2.5 on 2021-08-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20210830_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=1, max_length=64, verbose_name='登陆密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default=2, max_length=32, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
