# Generated by Django 3.2.5 on 2021-08-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210830_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='principal',
        ),
        migrations.AddField(
            model_name='company',
            name='principal',
            field=models.ManyToManyField(limit_choices_to={'depart__title': '管理层'}, related_name='principal', to='crm.UserInfo', verbose_name='负责人'),
        ),
    ]
